# Configuração para atualizar dependências de Python (pip)
  - package-ecosystem: "pip"
    directory: "/" # O 'requirements.txt' está na raiz do projeto
    schedule:
      interval: "weekly"
    # Adiciona uma mensagem de commit clara
    commit-message:
      prefix: "deps(pip)"
      include: "scope"

  # Configuração para atualizar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Verifica os workflows em .github/workflows
    schedule:
      interval: "weekly"
    # Adiciona uma mensagem de commit clara
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
